name: MUtils-Damage-Crash # Replace with your own plugin name. You can use the MUtils namespace to highlight the connection
load: STARTUP
version: 1.0.1 # Replace with your own plugin version. Should rise on updates
main: com.github.mooziii.damageCrash.CrashAddon # Replace your new main class (after changing namespace)
api-version: 1.16
authors: [ mooziii ] # Replace with your name
description: MUtils Damage Crash - Crashes your client in case of a skill issue! # Replace with your fancy description
softdepend: [ MUtils-Challenge ] # IMPORTANT - Keep this to load MChallenge before your plugin
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
  - "net.axay:kspigot:1.19.2"